import telebot
from telebot import types # для указание типов
bot = telebot.TeleBot('6295786342:AAEf7TXQohWOTEU7ouAQe6ezYuVLvog0rog')
@bot.message_handler(content_types=["text"])
def default_test(message):
        keyboard = types.InlineKeyboardMarkup()
        key1 = types.InlineKeyboardButton(text="Обучение 📚", callback_data="key1")
        key2 = types.InlineKeyboardButton(text="О Нас", callback_data="key2")
        standards = types.InlineKeyboardButton(text="Стандарты компании", callback_data="standards")
        services = types.InlineKeyboardButton(text="Наши услуги", callback_data="services")
        vacancies = types.InlineKeyboardButton(text="Вакансии", callback_data="vacancies")
        key3 = types.InlineKeyboardButton(text="Контакты", callback_data="key3")
        keyboard.add(key1)
        keyboard.add(standards)
        keyboard.add(services)
        keyboard.add(vacancies)
        keyboard.add(key3)
        keyboard.add(key2)
        bot.send_message(message.chat.id, "Привет! Я Родной Бот, давай я помогу тебе?", reply_markup=keyboard)
@bot.callback_query_handler(func=lambda call: True)
def callback_inline(call):
    if call.data == "keyboard":
        keyboard = types.InlineKeyboardMarkup()
        key1 = types.InlineKeyboardButton(text="Обучение 📚", callback_data="key1")
        key2 = types.InlineKeyboardButton(text="О Нас 🏡", callback_data="key2")
        standards = types.InlineKeyboardButton(text="Стандарты компании 📑", callback_data="standards")
        services = types.InlineKeyboardButton(text="Наши услуги 💰", callback_data="services")
        vacancies = types.InlineKeyboardButton(text="Вакансии📅", callback_data="vacancies")
        key3 = types.InlineKeyboardButton(text="Контакты 📩", callback_data="key3")
        keyboard.add(key1)
        keyboard.add(standards)
        keyboard.add(services)
        keyboard.add(vacancies)
        keyboard.add(key3)
        keyboard.add(key2)
        bot.edit_message_text('Привет! Я Родной Бот, давай я помогу тебе?', call.message.chat.id, call.message.message_id,reply_markup=keyboard)
    elif call.data == "key1":
        key1 = types.InlineKeyboardMarkup()
        hr = types.InlineKeyboardButton(text='HR Департамент 🙋‍♂', callback_data='hr')
        sales_department = types.InlineKeyboardButton(text='Отдел продаж 👨‍💼', callback_data='sales_department')
        administration = types.InlineKeyboardButton(text='Администрация 🧑‍💻', callback_data='administration')
        lawyer = types.InlineKeyboardButton(text='Юр. Отдел  🧑🏻‍💼', callback_data='lawyer')
        back = types.InlineKeyboardButton(text='Назад', callback_data='keyboard')
        key1.add(sales_department)
        key1.add(hr)
        key1.add(administration)
        key1.add(lawyer)
        key1.add(back)
        bot.edit_message_text('Здесь Вы найдете обучение для Вас', call.message.chat.id, call.message.message_id,reply_markup=key1)
    elif call.data == "key2":
        next_menu = types.InlineKeyboardMarkup()
        key4 = types.InlineKeyboardButton(text='Наш Сайт', url='https://vk.com/rodnoy_krov', callback_data='key4')
        back = types.InlineKeyboardButton(text='Назад', callback_data='keyboard')
        next_menu.add(back, key4)
        bot.edit_message_text('Здесь Вы можете узнать немного информации о нас', call.message.chat.id, call.message.message_id,reply_markup=next_menu)
    elif call.data == "key3":
        next_menu2 = types.InlineKeyboardMarkup()
        key5 = types.InlineKeyboardButton(text='Телефон РОПа', callback_data='key5')
        back = types.InlineKeyboardButton(text='Назад', callback_data='keyboard')
        next_menu2.add(back, key5)
        bot.edit_message_text('Телефоны и основные контакты', call.message.chat.id, call.message.message_id,
                              reply_markup=next_menu2)
    if call.data == "hr":
        hr = types.InlineKeyboardMarkup()
        hr_supervisor = types.InlineKeyboardButton(text="Руководитель Департамента", callback_data="hr_supervisor")
        hr_adaptation = types.InlineKeyboardButton(text="Отдел найма и адаптации", callback_data="hr_adaptation")
        hr_education = types.InlineKeyboardButton(text="Отдел обучения и повышения квалицикации", callback_data="hr_education")
        hr_efficiency = types.InlineKeyboardButton(text="Отдел по работе с эффективностью персонала", callback_data="hr_efficiency")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        back1 = types.InlineKeyboardButton(text="Назад", callback_data="key1")
        hr.add(hr_supervisor)
        hr.add(hr_adaptation)
        hr.add(hr_education)
        hr.add(hr_efficiency)
        hr.add(back, back1)
        bot.edit_message_text('Обучение для HR отдела', call.message.chat.id, call.message.message_id,reply_markup=hr)
    elif call.data == "hr_supervisor":
        hr_supervisor = types.InlineKeyboardMarkup()
        hr_supervisor_one = types.InlineKeyboardButton(text='HR руководитель 1 день', callback_data='hr_supervisor_one')
        hr_supervisor_two = types.InlineKeyboardButton(text='HR руководитель 2 день', callback_data='hr_supervisor_two')
        hr_supervisor_three = types.InlineKeyboardButton(text='HR руководитель 3 день', callback_data='hr_supervisor_three')
        hr_supervisor_regulations = types.InlineKeyboardButton(text='Регламенты HR руководитель', callback_data='hr_supervisor_regulations')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr = types.InlineKeyboardButton(text="Назад", callback_data="hr")
        hr_supervisor.add(hr_supervisor_one)
        hr_supervisor.add(hr_supervisor_two)
        hr_supervisor.add(hr_supervisor_three)
        hr_supervisor.add(hr_supervisor_regulations)
        hr_supervisor.add(back, hr)
        bot.edit_message_text('Обучение для руководителя HR', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor)
    elif call.data == "hr_adaptation":
        hr_adaptation = types.InlineKeyboardMarkup()
        hr_supervisor_calling = types.InlineKeyboardButton(text='Руководитель отдела найма', callback_data='hr_supervisor_calling')
        hr_manager_calling = types.InlineKeyboardButton(text='HR менеджер по обзвону', callback_data='hr_manager_calling')
        hr_manager_interview = types.InlineKeyboardButton(text='HR менеджер собеседований', callback_data='hr_manager_interview')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr = types.InlineKeyboardButton(text="Назад", callback_data="hr")
        hr_adaptation.add(hr_supervisor_calling)
        hr_adaptation.add(hr_manager_calling)
        hr_adaptation.add(hr_manager_interview)
        hr_adaptation.add(back, hr)
        bot.edit_message_text('Обучение для отдела найма и адаптации', call.message.chat.id, call.message.message_id,
                              reply_markup= hr_adaptation)
    if call.data == "hr_supervisor_one":
        hr_supervisor_one = types.InlineKeyboardMarkup()
        day1_hr = types.InlineKeyboardButton(text="Материал для изучения день 1", callback_data="day1_hr")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor")
        testing_hr_day1 = types.InlineKeyboardButton(text="Тесты директор HR день 1", callback_data="testing_hr_day1")
        hr_supervisor_one.add(day1_hr)
        hr_supervisor_one.add(testing_hr_day1)
        hr_supervisor_one.add(back, hr_supervisor)
        bot.edit_message_text('Обучение для HR руководителя день 1', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_one)
    if call.data == "hr_supervisor_two":
        hr_supervisor_two = types.InlineKeyboardMarkup()
        day2_hr = types.InlineKeyboardButton(text="Материал для изучения день 2", callback_data="day2_hr")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor")
        testing_hr_day2 = types.InlineKeyboardButton(text="Тесты директор HR день 2", callback_data="testing_hr_day2")
        hr_supervisor_two.add(day2_hr)
        hr_supervisor_two.add(testing_hr_day2)
        hr_supervisor_two.add(back, hr_supervisor)
        bot.edit_message_text('Обучение для HR руководителя день 2', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_two)
    if call.data == "hr_supervisor_three":
        hr_supervisor_three = types.InlineKeyboardMarkup()
        day3_hr = types.InlineKeyboardButton(text="Материал для изучения день 3", callback_data="day3_hr")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor")
        testing_hr_day3 = types.InlineKeyboardButton(text="Тесты директор HR день 3", callback_data="testing_hr_day3")
        hr_supervisor_three.add(day3_hr)
        hr_supervisor_three.add(testing_hr_day3)
        hr_supervisor_three.add(back, hr_supervisor)
        bot.edit_message_text('Обучение для HR руководителя день 3', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_three)
    if call.data == "hr_supervisor_calling":
        hr_supervisor_calling = types.InlineKeyboardMarkup()
        hr_supervisor_calling_day1 = types.InlineKeyboardButton(text="Руководитель отдела найма день 1", callback_data="hr_supervisor_calling_day1")
        hr_supervisor_calling_day2 = types.InlineKeyboardButton(text="Руководитель отдела найма день 2", callback_data="hr_supervisor_calling_day2")
        hr_supervisor_calling_day3 = types.InlineKeyboardButton(text="Руководитель отдела найма день 3", callback_data="hr_supervisor_calling_day3")
        hr_manager_calling_regulations = types.InlineKeyboardButton(text="Регламенты Руководителя отдела найма", callback_data="hr_manager_calling_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_adaptation = types.InlineKeyboardButton(text="Назад", callback_data="hr_adaptation")
        hr_supervisor_calling.add(hr_supervisor_calling_day1)
        hr_supervisor_calling.add(hr_supervisor_calling_day2)
        hr_supervisor_calling.add(hr_supervisor_calling_day3)
        hr_supervisor_calling.add(hr_manager_calling_regulations)
        hr_supervisor_calling.add(back, hr_adaptation)
        bot.edit_message_text('Обучение для Руководителя отдела найма', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_calling)
    elif call.data == "hr_supervisor_calling_day1":
        hr_supervisor_calling_day1 = types.InlineKeyboardMarkup()
        hr_supervisor_calling_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_supervisor_calling_day1_material')
        hr_supervisor_calling_day1_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела найма день 1',callback_data='hr_supervisor_calling_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_calling")
        hr_supervisor_calling_day1.add(hr_supervisor_calling_day1_material)
        hr_supervisor_calling_day1.add(hr_supervisor_calling_day1_testing)
        hr_supervisor_calling_day1.add(back, hr_supervisor_calling)
        bot.edit_message_text('Обучение для Руководителя отдела найма день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_calling_day1)
    elif call.data == "hr_supervisor_calling_day2":
        hr_supervisor_calling_day2 = types.InlineKeyboardMarkup()
        hr_supervisor_calling_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_supervisor_calling_day1_material')
        hr_supervisor_calling_day2_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела найма день 2',callback_data='hr_supervisor_calling_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_calling")
        hr_supervisor_calling_day2.add(hr_supervisor_calling_day2_material)
        hr_supervisor_calling_day2.add(hr_supervisor_calling_day2_testing)
        hr_supervisor_calling_day2.add(back, hr_supervisor_calling)
        bot.edit_message_text('Обучение для Руководителя отдела найма день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_calling_day2)
    elif call.data == "hr_supervisor_calling_day3":
        hr_supervisor_calling_day3 = types.InlineKeyboardMarkup()
        hr_supervisor_calling_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_supervisor_calling_day3_material')
        hr_supervisor_calling_day3_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела найма день 2',callback_data='hr_supervisor_calling_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_calling")
        hr_supervisor_calling_day3.add(hr_supervisor_calling_day3_material)
        hr_supervisor_calling_day3.add(hr_supervisor_calling_day3_testing)
        hr_supervisor_calling_day3.add(back, hr_supervisor_calling)
        bot.edit_message_text('Обучение для Руководителя отдела найма день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_calling_day3)
    if call.data == "hr_manager_calling":
        hr_manager_calling = types.InlineKeyboardMarkup()
        hr_manager_calling_day1 = types.InlineKeyboardButton(text="HR менеджер по обзвону день 1", callback_data="hr_manager_calling_day1")
        hr_manager_calling_day2 = types.InlineKeyboardButton(text="HR менеджер по обзвону день 2", callback_data="hr_manager_calling_day2")
        hr_manager_calling_day3 = types.InlineKeyboardButton(text="HR менеджер по обзвону день 3", callback_data="hr_manager_calling_day3")
        hr_manager_calling_regulations = types.InlineKeyboardButton(text="Регламенты HR менеджера по обзвону", callback_data="hr_manager_calling_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_adaptation = types.InlineKeyboardButton(text="Назад", callback_data="hr_adaptation")
        hr_manager_calling.add(hr_manager_calling_day1)
        hr_manager_calling.add(hr_manager_calling_day2)
        hr_manager_calling.add(hr_manager_calling_day3)
        hr_manager_calling.add(hr_manager_calling_regulations)
        hr_manager_calling.add(back, hr_adaptation)
        bot.edit_message_text('Обучение для HR менеджера по обзвону', call.message.chat.id, call.message.message_id,reply_markup=hr_manager_calling)
    elif call.data == "hr_manager_calling_day1":
        hr_manager_calling_day1 = types.InlineKeyboardMarkup()
        hr_manager_calling_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_manager_calling_day1_material')
        hr_manager_calling_day1_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по обзвону день 1',callback_data='hr_manager_calling_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_calling")
        hr_manager_calling_day1.add(hr_manager_calling_day1_material)
        hr_manager_calling_day1.add(hr_manager_calling_day1_testing)
        hr_manager_calling_day1.add(back, hr_manager_calling)
        bot.edit_message_text('Обучение для HR менеджера по обзвону день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_calling_day1)
    elif call.data == "hr_manager_calling_day2":
        hr_manager_calling_day2 = types.InlineKeyboardMarkup()
        hr_manager_calling_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_manager_calling_day2_material')
        hr_manager_calling_day2_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по обзвону день 2',callback_data='hr_manager_calling_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_calling")
        hr_manager_calling_day2.add(hr_manager_calling_day2_material)
        hr_manager_calling_day2.add(hr_manager_calling_day2_testing)
        hr_manager_calling_day2.add(back, hr_manager_calling)
        bot.edit_message_text('Обучение для HR менеджера по обзвону день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_calling_day2)
    elif call.data == "hr_manager_calling_day3":
        hr_manager_calling_day3 = types.InlineKeyboardMarkup()
        hr_manager_calling_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',callback_data='hr_manager_calling_day3_material')
        hr_manager_calling_day3_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по обзвону день 3',callback_data='hr_manager_calling_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_calling = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_calling")
        hr_manager_calling_day3.add(hr_manager_calling_day3_material)
        hr_manager_calling_day3.add(hr_manager_calling_day3_testing)
        hr_manager_calling_day3.add(back, hr_manager_calling)
        bot.edit_message_text('Обучение для HR менеджера по обзвону день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_calling_day3)
    if call.data == "hr_manager_interview":
        hr_manager_interview = types.InlineKeyboardMarkup()
        hr_manager_interview_day1 = types.InlineKeyboardButton(text="HR менеджер по собеседованиям день 1", callback_data="hr_manager_interview_day1")
        hr_manager_interview_day2 = types.InlineKeyboardButton(text="HR менеджер по собеседованиям день 2", callback_data="hr_manager_interview_day2")
        hr_manager_interview_day3 = types.InlineKeyboardButton(text="HR менеджер по собеседованиям день 3", callback_data="hr_manager_interview_day3")
        hr_manager_interview_regulations = types.InlineKeyboardButton(text="Регламенты HR менеджера по собеседованиям", callback_data="hr_manager_calling_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_adaptation = types.InlineKeyboardButton(text="Назад", callback_data="hr_adaptation")
        hr_manager_interview.add(hr_manager_interview_day1)
        hr_manager_interview.add(hr_manager_interview_day2)
        hr_manager_interview.add(hr_manager_interview_day3)
        hr_manager_interview.add(hr_manager_interview_regulations)
        hr_manager_interview.add(back, hr_adaptation)
        bot.edit_message_text('Обучение для HR менеджера по собеседованиям', call.message.chat.id, call.message.message_id,reply_markup=hr_manager_interview)
    elif call.data == "hr_manager_interview_day1":
        hr_manager_interview_day1 = types.InlineKeyboardMarkup()
        hr_manager_interview_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_manager_interview_day1_material')
        hr_manager_interview_day1_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по собеседованиям день 1',callback_data='hr_manager_interview_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_interview = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_interview")
        hr_manager_interview_day1.add(hr_manager_interview_day1_material)
        hr_manager_interview_day1.add(hr_manager_interview_day1_testing)
        hr_manager_interview_day1.add(back, hr_manager_interview)
        bot.edit_message_text('Обучение для HR менеджера по собеседованиям день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_interview_day1)
    elif call.data == "hr_manager_interview_day2":
        hr_manager_interview_day2 = types.InlineKeyboardMarkup()
        hr_manager_interview_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_manager_interview_day2_material')
        hr_manager_interview_day2_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по собеседованиям день 2',callback_data='hr_manager_interview_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_interview = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_interview")
        hr_manager_interview_day2.add(hr_manager_interview_day2_material)
        hr_manager_interview_day2.add(hr_manager_interview_day2_testing)
        hr_manager_interview_day2.add(back, hr_manager_interview)
        bot.edit_message_text('Обучение для HR менеджера по собеседованиям день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_interview_day2)
    elif call.data == "hr_manager_interview_day3":
        hr_manager_interview_day3 = types.InlineKeyboardMarkup()
        hr_manager_interview_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',callback_data='hr_manager_interview_day3_material')
        hr_manager_interview_day3_testing = types.InlineKeyboardButton(text='Тесты HR менеджер по собеседованиям день 3',callback_data='hr_manager_interview_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_interview = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_interview")
        hr_manager_interview_day3.add(hr_manager_interview_day3_material)
        hr_manager_interview_day3.add(hr_manager_interview_day3_testing)
        hr_manager_interview_day3.add(back, hr_manager_interview)
        bot.edit_message_text('Обучение для HR менеджера по собеседованиям день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_interview_day3)
    elif call.data == "hr_education":
        hr_education = types.InlineKeyboardMarkup()
        hr_supervisor_education = types.InlineKeyboardButton(text='Руководитель отдела обучения', callback_data='hr_supervisor_education')
        hr_manager_education = types.InlineKeyboardButton(text='HR менеджер по обучению', callback_data='hr_manager_education')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr = types.InlineKeyboardButton(text="Назад", callback_data="hr")
        hr_education.add(hr_supervisor_education)
        hr_education.add(hr_manager_education)
        hr_education.add(back, hr)
        bot.edit_message_text('Обучение для отдела обучения и повышения квалификации', call.message.chat.id, call.message.message_id,
                              reply_markup= hr_education)
    if call.data == "hr_supervisor_education":
        hr_supervisor_education = types.InlineKeyboardMarkup()
        hr_supervisor_education_day1 = types.InlineKeyboardButton(text="Руководитель отдела обучения день 1", callback_data="hr_supervisor_education_day1")
        hr_supervisor_education_day2 = types.InlineKeyboardButton(text="Руководитель отдела обучения день 2", callback_data="hr_supervisor_education_day2")
        hr_supervisor_education_day3 = types.InlineKeyboardButton(text="Руководитель отдела обучения день 3", callback_data="hr_supervisor_education_day3")
        hr_supervisor_education_regulations = types.InlineKeyboardButton(text="Регламенты Руководителя отдела обучения", callback_data="hr_supervisor_education_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_education")
        hr_supervisor_education.add(hr_supervisor_education_day1)
        hr_supervisor_education.add(hr_supervisor_education_day2)
        hr_supervisor_education.add(hr_supervisor_education_day3)
        hr_supervisor_education.add(hr_supervisor_education_regulations)
        hr_supervisor_education.add(back, hr_education)
        bot.edit_message_text('Обучение для Руководителя отдела обучения', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_education)
    elif call.data == "hr_supervisor_education_day1":
        hr_supervisor_education_day1 = types.InlineKeyboardMarkup()
        hr_manager_interview_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_manager_interview_day1_material')
        hr_manager_interview_day1_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела обучения день 1',callback_data='hr_manager_interview_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_education")
        hr_supervisor_education_day1.add(hr_manager_interview_day1_material)
        hr_supervisor_education_day1.add(hr_manager_interview_day1_testing)
        hr_supervisor_education_day1.add(back, hr_supervisor_education)
        bot.edit_message_text('Обучение для Руководителя отдела обучения день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_education_day1)
    elif call.data == "hr_supervisor_education_day2":
        hr_supervisor_education_day2 = types.InlineKeyboardMarkup()
        hr_supervisor_education_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_supervisor_education_day2_material')
        hr_supervisor_education_day2_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела обучения день 2',callback_data='hr_supervisor_education_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_education")
        hr_supervisor_education_day2.add(hr_supervisor_education_day2_material)
        hr_supervisor_education_day2.add(hr_supervisor_education_day2_testing)
        hr_supervisor_education_day2.add(back, hr_supervisor_education)
        bot.edit_message_text('Обучение для Руководителя отдела обучения день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_education_day2)
    elif call.data == "hr_supervisor_education_day3":
        hr_supervisor_education_day3 = types.InlineKeyboardMarkup()
        hr_supervisor_education_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',callback_data='hr_supervisor_education_day3_material')
        hr_supervisor_education_day3_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела обучения день 3',callback_data='hr_supervisor_education_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_education")
        hr_supervisor_education_day3.add(hr_supervisor_education_day3_material)
        hr_supervisor_education_day3.add(hr_supervisor_education_day3_testing)
        hr_supervisor_education_day3.add(back, hr_supervisor_education)
        bot.edit_message_text('Обучение для Руководителя отдела обучения день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_education_day3)
    if call.data == "hr_manager_education":
        hr_manager_education = types.InlineKeyboardMarkup()
        hr_manager_education_day1 = types.InlineKeyboardButton(text="HR менеджер по обучению день 1", callback_data="hr_manager_education_day1")
        hr_manager_education_day2 = types.InlineKeyboardButton(text="HR менеджер по обучению день 2", callback_data="hr_manager_education_day2")
        hr_manager_education_day3 = types.InlineKeyboardButton(text="HR менеджер по обучению день 3", callback_data="hr_manager_education_day3")
        hr_manager_education_regulations = types.InlineKeyboardButton(text="Регламенты HR менеджера по обучению", callback_data="hr_manager_education_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_education")
        hr_manager_education.add(hr_manager_education_day1)
        hr_manager_education.add(hr_manager_education_day2)
        hr_manager_education.add(hr_manager_education_day3)
        hr_manager_education.add(hr_manager_education_regulations)
        hr_manager_education.add(back, hr_education)
        bot.edit_message_text('Обучение HR менеджера по обучению', call.message.chat.id, call.message.message_id,reply_markup=hr_manager_education)
    elif call.data == "hr_manager_education_day1":
        hr_manager_education_day1 = types.InlineKeyboardMarkup()
        hr_manager_interview_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_manager_interview_day1_material')
        hr_manager_interview_day1_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по обучению день 1',callback_data='hr_manager_interview_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_education")
        hr_manager_education_day1.add(hr_manager_interview_day1_material)
        hr_manager_education_day1.add(hr_manager_interview_day1_testing)
        hr_manager_education_day1.add(back, hr_manager_education)
        bot.edit_message_text('Обучение для HR менеджера по обучению день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_education_day1)
    elif call.data == "hr_manager_education_day2":
        hr_manager_education_day2 = types.InlineKeyboardMarkup()
        hr_manager_education_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_manager_education_day2_material')
        hr_manager_education_day2_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по обучению день 2',callback_data='hr_manager_education_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_education")
        hr_manager_education_day2.add(hr_manager_education_day2_material)
        hr_manager_education_day2.add(hr_manager_education_day2_testing)
        hr_manager_education_day2.add(back, hr_manager_education)
        bot.edit_message_text('Обучение для HR менеджера по обучению день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_education_day2)
    elif call.data == "hr_manager_education_day3":
        hr_manager_education_day3 = types.InlineKeyboardMarkup()
        hr_manager_education_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',callback_data='hr_manager_education_day3_material')
        hr_manager_education_day3_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по обучению день 3',callback_data='hr_manager_education_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_education = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_education")
        hr_manager_education_day3.add(hr_manager_education_day3_material)
        hr_manager_education_day3.add(hr_manager_education_day3_testing)
        hr_manager_education_day3.add(back, hr_manager_education)
        bot.edit_message_text('Обучение для HR менеджера по обучению день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_education_day3)
    elif call.data == "hr_efficiency":
        hr_efficiency = types.InlineKeyboardMarkup()
        hr_supervisor_efficiency = types.InlineKeyboardButton(text='Руководитель отдела эффективности', callback_data='hr_supervisor_efficiency')
        hr_manager_efficiency = types.InlineKeyboardButton(text='HR менеджер по эффективности персонала', callback_data='hr_manager_efficiency')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr = types.InlineKeyboardButton(text="Назад", callback_data="hr")
        hr_efficiency.add(hr_supervisor_efficiency)
        hr_efficiency.add(hr_manager_efficiency)
        hr_efficiency.add(back, hr)
        bot.edit_message_text('Обучение для отдела по работе с эффективностью персонала', call.message.chat.id, call.message.message_id,
                              reply_markup= hr_efficiency)
    if call.data == "hr_supervisor_efficiency":
        hr_supervisor_efficiency = types.InlineKeyboardMarkup()
        hr_supervisor_efficiency_day1 = types.InlineKeyboardButton(text="Руководитель отдела по работе с эффективностью персонала день 1", callback_data="hr_supervisor_efficiency_day1")
        hr_supervisor_efficiency_day2 = types.InlineKeyboardButton(text="Руководитель отдела по работе с эффективностью персонала день 2", callback_data="hr_supervisor_efficiency_day2")
        hr_supervisor_efficiency_day3 = types.InlineKeyboardButton(text="Руководитель отдела по работе с эффективностью персонала день 3", callback_data="hr_supervisor_efficiency_day3")
        hr_supervisor_efficiency_regulations = types.InlineKeyboardButton(text="Регламенты Руководителя отдела по работе с эффективностью персонала", callback_data="hr_supervisor_efficiency_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_efficiency")
        hr_supervisor_efficiency.add(hr_supervisor_efficiency_day1)
        hr_supervisor_efficiency.add(hr_supervisor_efficiency_day2)
        hr_supervisor_efficiency.add(hr_supervisor_efficiency_day3)
        hr_supervisor_efficiency.add(hr_supervisor_efficiency_regulations)
        hr_supervisor_efficiency.add(back, hr_efficiency)
        bot.edit_message_text('Обучение для Руководителя отдела по работе с эффективностью персонала', call.message.chat.id, call.message.message_id,reply_markup=hr_supervisor_efficiency)
    elif call.data == "hr_supervisor_efficiency_day1":
        hr_supervisor_efficiency_day1 = types.InlineKeyboardMarkup()
        hr_supervisor_efficiency_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',callback_data='hr_supervisor_efficiency_day1_material')
        hr_supervisor_efficiency_day1_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела по работе с эффективностью персонала 1',callback_data='hr_supervisor_efficiency_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_efficiency")
        hr_supervisor_efficiency_day1.add(hr_supervisor_efficiency_day1_material)
        hr_supervisor_efficiency_day1.add(hr_supervisor_efficiency_day1_testing)
        hr_supervisor_efficiency_day1.add(back, hr_supervisor_efficiency)
        bot.edit_message_text('Обучение для Руководителя отдела по работе с эффективностью персонала день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_efficiency_day1)
    elif call.data == "hr_supervisor_efficiency_day2":
        hr_supervisor_efficiency_day2 = types.InlineKeyboardMarkup()
        hr_supervisor_efficiency_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',callback_data='hr_supervisor_efficiency_day2_material')
        hr_supervisor_efficiency_day2_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела по работе с эффективностью персонала 2',callback_data='hr_supervisor_efficiency_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_efficiency")
        hr_supervisor_efficiency_day2.add(hr_supervisor_efficiency_day2_material)
        hr_supervisor_efficiency_day2.add(hr_supervisor_efficiency_day2_testing)
        hr_supervisor_efficiency_day2.add(back, hr_supervisor_efficiency)
        bot.edit_message_text('Обучение для Руководителя отдела по работе с эффективностью персонала день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_efficiency_day2)
    elif call.data == "hr_supervisor_efficiency_day3":
        hr_supervisor_efficiency_day3 = types.InlineKeyboardMarkup()
        hr_supervisor_efficiency_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',callback_data='hr_supervisor_efficiency_day3_material')
        hr_supervisor_efficiency_day3_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела по работе с эффективностью персонала 3',callback_data='hr_supervisor_efficiency_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_supervisor_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_supervisor_efficiency")
        hr_supervisor_efficiency_day3.add(hr_supervisor_efficiency_day3_material)
        hr_supervisor_efficiency_day3.add(hr_supervisor_efficiency_day3_testing)
        hr_supervisor_efficiency_day3.add(back, hr_supervisor_efficiency)
        bot.edit_message_text('Обучение для Руководителя отдела по работе с эффективностью персонала день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_supervisor_efficiency_day3)
    if call.data == "hr_manager_efficiency":
        hr_manager_efficiency = types.InlineKeyboardMarkup()
        hr_manager_efficiency_day1 = types.InlineKeyboardButton(text="HR менеджер по эффективности персонала день 1",
                                                                callback_data="hr_manager_efficiency_day1")
        hr_manager_efficiency_day2 = types.InlineKeyboardButton(text="HR менеджер по эффективности персонала день 2",
                                                                callback_data="hr_manager_efficiency_day2")
        hr_manager_efficiency_day3 = types.InlineKeyboardButton(text="HR менеджер по эффективности персонала день 3",
                                                                callback_data="hr_manager_efficiency_day3")
        hr_manager_efficiency_regulations = types.InlineKeyboardButton(text="Регламенты HR менеджера по эффективности персонала",
                                                                          callback_data="hr_manager_efficiency_regulations")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_efficiency")
        hr_manager_efficiency.add(hr_manager_efficiency_day1)
        hr_manager_efficiency.add(hr_manager_efficiency_day2)
        hr_manager_efficiency.add(hr_manager_efficiency_day3)
        hr_manager_efficiency.add(hr_manager_efficiency_regulations)
        hr_manager_efficiency.add(back, hr_efficiency)
        bot.edit_message_text('Обучение для HR менеджера по эффективности персонала',
                              call.message.chat.id, call.message.message_id,reply_markup=hr_manager_efficiency)
    elif call.data == "hr_manager_efficiency_day1":
        hr_manager_efficiency_day1 = types.InlineKeyboardMarkup()
        hr_manager_efficiency_day1_material = types.InlineKeyboardButton(text='Материал для изучения день 1',
                                                                         callback_data='hr_manager_efficiency_day1_material')
        hr_manager_efficiency_day1_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по эффективности персонала день 1',
                                                                        callback_data='hr_manager_efficiency_day1_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_efficiency")
        hr_manager_efficiency_day1.add(hr_manager_efficiency_day1_material)
        hr_manager_efficiency_day1.add(hr_manager_efficiency_day1_testing)
        hr_manager_efficiency_day1.add(back, hr_manager_efficiency)
        bot.edit_message_text('Обучение для HR менеджера по эффективности персонала день 1', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_efficiency_day1)
    elif call.data == "hr_manager_efficiency_day2":
        hr_manager_efficiency_day2 = types.InlineKeyboardMarkup()
        hr_manager_efficiency_day2_material = types.InlineKeyboardButton(text='Материал для изучения день 2',
                                                                         callback_data='hr_manager_efficiency_day2_material')
        hr_manager_efficiency_day2_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по эффективности персонала день 2',
                                                                        callback_data='hr_manager_efficiency_day2_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_efficiency")
        hr_manager_efficiency_day2.add(hr_manager_efficiency_day2_material)
        hr_manager_efficiency_day2.add(hr_manager_efficiency_day2_testing)
        hr_manager_efficiency_day2.add(back, hr_manager_efficiency)
        bot.edit_message_text('Обучение для HR менеджера по эффективности персонала день 2', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_efficiency_day2)
    elif call.data == "hr_manager_efficiency_day3":
        hr_manager_efficiency_day3 = types.InlineKeyboardMarkup()
        hr_manager_efficiency_day3_material = types.InlineKeyboardButton(text='Материал для изучения день 3',
                                                                         callback_data='hr_manager_efficiency_day3_material')
        hr_manager_efficiency_day3_testing = types.InlineKeyboardButton(text='Тесты HR менеджера по эффективности персонала день 3',
                                                                        callback_data='hr_manager_efficiency_day3_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        hr_manager_efficiency = types.InlineKeyboardButton(text="Назад", callback_data="hr_manager_efficiency")
        hr_manager_efficiency_day3.add(hr_manager_efficiency_day3_material)
        hr_manager_efficiency_day3.add(hr_manager_efficiency_day3_testing)
        hr_manager_efficiency_day3.add(back, hr_manager_efficiency)
        bot.edit_message_text('Обучение для HR менеджера по эффективности персонала день 3', call.message.chat.id, call.message.message_id,
                              reply_markup=hr_manager_efficiency_day3)

    if call.data == "sales_department":
        sales_department = types.InlineKeyboardMarkup()
        agent = types.InlineKeyboardButton(text="Агент", callback_data="agent")
        rop = types.InlineKeyboardButton(text="Руководитель отдела продаж", callback_data="rop")
        director_sales = types.InlineKeyboardButton(text="Директор отдела продаж", callback_data="director_sales")
        cross = types.InlineKeyboardButton(text="Кросс-менеджер", callback_data="cross")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        back1 = types.InlineKeyboardButton(text="Назад", callback_data="key1")
        sales_department.add(director_sales)
        sales_department.add(rop)
        sales_department.add(agent)
        sales_department.add(cross)
        sales_department.add(back, back1)
        bot.edit_message_text('Обучение для Отдела Продаж', call.message.chat.id, call.message.message_id,
                                  reply_markup=sales_department)
    elif call.data == "rop":
        rop = types.InlineKeyboardMarkup()
        rop_one = types.InlineKeyboardButton(text='Руководитель отдела продаж 1 день', callback_data='rop_one')
        rop_two = types.InlineKeyboardButton(text='Руководитель отдела продаж 2 день', callback_data='rop_two')
        rop_three = types.InlineKeyboardButton(text='Руководитель отдела продаж 3 день', callback_data='rop_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        sales_department = types.InlineKeyboardButton(text="Назад", callback_data="sales_department")
        rop.add(rop_one)
        rop.add(rop_two)
        rop.add(rop_three)
        rop.add(back, sales_department)
        bot.edit_message_text('Обучение для Руководителя отдела продаж', call.message.chat.id, call.message.message_id,
                                  reply_markup=rop)
    if call.data == "rop_one":
        rop_one = types.InlineKeyboardMarkup()
        rop_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день', callback_data='rop_one_material')
        rop_one_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела продаж 1 день', callback_data='director_sales_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        rop = types.InlineKeyboardButton(text="Назад", callback_data="rop")
        rop_one.add(rop_one_material)
        rop_one.add(rop_one_testing)
        rop_one.add(back, rop)
        bot.edit_message_text('Обучение для Руководителя отдела продаж день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=rop_one)
    if call.data == "rop_two":
        rop_two = types.InlineKeyboardMarkup()
        rop_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', callback_data='rop_two_material')
        rop_two_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела продаж 2 день', callback_data='rop_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        rop = types.InlineKeyboardButton(text="Назад", callback_data="rop")
        rop_two.add(rop_two_material)
        rop_two.add(rop_two_testing)
        rop_two.add(back, rop)
        bot.edit_message_text('Обучение для Руководителя отдела продаж день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=rop_two)
    if call.data == "rop_three":
        rop_three = types.InlineKeyboardMarkup()
        rop_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день', callback_data='rop_three_material')
        rop_three_testing = types.InlineKeyboardButton(text='Тесты Руководителя отдела продаж 3 день', callback_data='rop_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        rop = types.InlineKeyboardButton(text="Назад", callback_data="rop")
        rop_three.add(rop_three_material)
        rop_three.add(rop_three_testing)
        rop_three.add(back, rop)
        bot.edit_message_text('Обучение для Руководителя отдела продаж день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=rop_three)
    elif call.data == "agent":
        agent = types.InlineKeyboardMarkup()
        agent_one = types.InlineKeyboardButton(text='Агент 1 день', callback_data='agent_one')
        agent_two = types.InlineKeyboardButton(text='Агент 2 день', callback_data='agent_two')
        agent_three = types.InlineKeyboardButton(text='Агент 3 день', callback_data='agent_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        sales_department = types.InlineKeyboardButton(text="Назад", callback_data="sales_department")
        agent.add(agent_one)
        agent.add(agent_two)
        agent.add(agent_three)
        agent.add(back, sales_department)
        bot.edit_message_text('Обучение для Агентов', call.message.chat.id, call.message.message_id,
                                  reply_markup=agent)
    if call.data == "agent_one":
        agent_one = types.InlineKeyboardMarkup()
        agent_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день',
                                                       url='https://drive.google.com/drive/folders/1GXWUHthzXzePtBVkWZMxQk69G6TQ9_gI?usp=share_link', callback_data='agent_one_material')
        agent_one_testing = types.InlineKeyboardButton(text='Тесты Агента 1 день',
                                                       url= 'https://docs.google.com/forms/d/e/1FAIpQLSfHNZITmOU1N4LKa4gNRrs370uAgdKIP3Xb9LRaJINRRe3wWg/viewform?usp=sf_link', callback_data='agent_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        agent = types.InlineKeyboardButton(text="Назад", callback_data="agent")
        agent_one.add(agent_one_material)
        agent_one.add(agent_one_testing)
        agent_one.add(back, agent)
        bot.edit_message_text('Обучение для Агента день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=agent_one)
    if call.data == "agent_two":
        agent_two = types.InlineKeyboardMarkup()
        agent_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', url='https://drive.google.com/drive/folders/1AuI9SU7mkFB8tMfYwR0rODD1aioLzvU1?usp=share_link', callback_data='agent_two_material')
        agent_two_testing = types.InlineKeyboardButton(text='Тесты Агента 2 день',url='https://docs.google.com/forms/d/e/1FAIpQLSdX_TpuigND5zlb3EXEnq1dxIFAdel5neI_dAcQ9UBpTxAKsQ/viewform?usp=sf_link', callback_data='agent_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        agent_two_video = types.InlineKeyboardButton(text="Видео о CRM", url='https://youtu.be/dRWBeaGLwzw', callback_data="agent_two_video")
        agent = types.InlineKeyboardButton(text="Назад", callback_data="agent")
        agent_two.add(agent_two_material)
        agent_two.add(agent_two_video)
        agent_two.add(agent_two_testing)
        agent_two.add(back, agent)
        bot.edit_message_text('Обучение для Агента день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=agent_two)
    if call.data == "agent_three":
        agent_three = types.InlineKeyboardMarkup()
        agent_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день', url= 'https://drive.google.com/drive/folders/1IsVZy7NtxAeSVgMgj2CcJRSy4e3oOGi2?usp=share_link', callback_data='agent_three_material')
        agent_three_testing = types.InlineKeyboardButton(text='Тесты Агента 3 день', url='https://docs.google.com/forms/d/e/1FAIpQLSckUI7T58iKnAv2OawbixiiGzIrUfnOj17XzYypwc0qlEQNiQ/viewform?usp=sf_link', callback_data='agent_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        agent = types.InlineKeyboardButton(text="Назад", callback_data="agent")
        agent_three.add(agent_three_material)
        agent_three.add(agent_three_testing)
        agent_three.add(back, agent)
        bot.edit_message_text('Обучение для Агента день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=agent_three)
    elif call.data == "director_sales":
        director_sales = types.InlineKeyboardMarkup()
        director_sales_one = types.InlineKeyboardButton(text='Директор по продажам 1 день',
                                                        callback_data='director_sales_one')
        director_sales_two = types.InlineKeyboardButton(text='Директор по продажам 2 день',
                                                        callback_data='director_sales_two')
        director_sales_three = types.InlineKeyboardButton(text='Директор по продажам 3 день',
                                                          callback_data='director_sales_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        sales_department = types.InlineKeyboardButton(text="Назад", callback_data="sales_department")
        director_sales.add(director_sales_one)
        director_sales.add(director_sales_two)
        director_sales.add(director_sales_three)
        director_sales.add(back, sales_department)
        bot.edit_message_text('Обучение для Директора по продажам', call.message.chat.id, call.message.message_id,
                              reply_markup=director_sales)
    if call.data == "director_sales_two":
        director_sales_two = types.InlineKeyboardMarkup()
        director_sales_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', callback_data='director_sales_two_material')
        director_sales_two_testing = types.InlineKeyboardButton(text='Тесты Директора по продажам 2 день', callback_data='director_sales_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_sales = types.InlineKeyboardButton(text="Назад", callback_data="director_sales")
        director_sales_two.add(director_sales_two_material)
        director_sales_two.add(director_sales_two_testing)
        director_sales_two.add(back, director_sales)
        bot.edit_message_text('Обучение для Директора по продажам день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_sales_two)
    if call.data == "director_sales_three":
        director_sales_three = types.InlineKeyboardMarkup()
        director_sales_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день', callback_data='director_sales_three_material')
        director_sales_three_testing = types.InlineKeyboardButton(text='Тесты Директора по продажам 3 день', callback_data='director_sales_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_sales = types.InlineKeyboardButton(text="Назад", callback_data="director_sales")
        director_sales_three.add(director_sales_three_material)
        director_sales_three.add(director_sales_three_testing)
        director_sales_three.add(back, director_sales)
        bot.edit_message_text('Обучение для Директора по продажам день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_sales_three)
    if call.data == "director_sales_one":
        director_sales_one = types.InlineKeyboardMarkup()
        director_sales_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день', callback_data='director_sales_one_material')
        director_sales_one_testing = types.InlineKeyboardButton(text='Тесты Директора по продажам 1 день', callback_data='director_sales_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_sales = types.InlineKeyboardButton(text="Назад", callback_data="director_sales")
        director_sales_one.add(director_sales_one_material)
        director_sales_one.add(director_sales_one_testing)
        director_sales_one.add(back, director_sales)
        bot.edit_message_text('Обучение для Директора по продажам день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_sales_one)
    elif call.data == "cross":
        cross = types.InlineKeyboardMarkup()
        cross_one = types.InlineKeyboardButton(text='Кросс-менеджер 1 день', callback_data='cross_one')
        cross_two = types.InlineKeyboardButton(text='Кросс-менеджер 2 день', callback_data='cross_two')
        cross_three = types.InlineKeyboardButton(text='Кросс-менеджер 3 день', callback_data='cross_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        sales_department = types.InlineKeyboardButton(text="Назад", callback_data="sales_department")
        cross.add(cross_one)
        cross.add(cross_two)
        cross.add(cross_three)

        cross.add(back, sales_department)
        bot.edit_message_text('Обучение для Директора по продажам', call.message.chat.id, call.message.message_id,
                                  reply_markup=cross)
    if call.data == "cross_one":
        cross_one = types.InlineKeyboardMarkup()
        cross_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день', callback_data='cross_one_material')
        cross_one_testing = types.InlineKeyboardButton(text='Тесты Кросс-менеджера 1 день', callback_data='cross_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        cross = types.InlineKeyboardButton(text="Назад", callback_data="cross")
        cross_one.add(cross_one_material)
        cross_one.add(cross_one_testing)
        cross_one.add(back, cross)
        bot.edit_message_text('Обучение для Кросс-менеджера день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=cross_one)
    if call.data == "cross_two":
        cross_two = types.InlineKeyboardMarkup()
        cross_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', callback_data='cross_two_material')
        cross_two_testing = types.InlineKeyboardButton(text='Тесты Кросс-менеджера 2 день', callback_data='cross_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        cross = types.InlineKeyboardButton(text="Назад", callback_data="cross")
        cross_two.add(cross_two_material)
        cross_two.add(cross_two_testing)
        cross_two.add(back, cross)
        bot.edit_message_text('Обучение для Кросс-менеджера день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=cross_two)
    if call.data == "cross_three":
        cross_three = types.InlineKeyboardMarkup()
        cross_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день', callback_data='cross_three_material')
        cross_three_testing = types.InlineKeyboardButton(text='Тесты Кросс-менеджера 3 день', callback_data='cross_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        cross = types.InlineKeyboardButton(text="Назад", callback_data="cross")
        cross_three.add(cross_three_material)
        cross_three.add(cross_three_testing)
        cross_three.add(back, cross)
        bot.edit_message_text('Обучение для Кросс-менеджера день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=cross_three)
    if call.data == "administration":
        administration = types.InlineKeyboardMarkup()
        office_manager = types.InlineKeyboardButton(text="Офис-менеджер", callback_data="office_manager")
        director_assistant = types.InlineKeyboardButton(text="Ассистент руководителя", callback_data="director_assistant")
        office_director = types.InlineKeyboardButton(text="Директор офиса", callback_data="office_director")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        back1 = types.InlineKeyboardButton(text="Назад", callback_data="key1")
        administration.add(office_director)
        administration.add(director_assistant)
        administration.add(office_manager)
        administration.add(back, back1)
        bot.edit_message_text('Обучение для Админ.Состава', call.message.chat.id, call.message.message_id,
                                  reply_markup=administration)
    elif call.data == "office_manager":
        office_manager = types.InlineKeyboardMarkup()
        office_manager_one = types.InlineKeyboardButton(text='Офис-менеджер 1 день', callback_data='office_manager_one')
        office_manager_two = types.InlineKeyboardButton(text='Офис-менеджер 2 день', callback_data='office_manager_two')
        office_manager_three = types.InlineKeyboardButton(text='Офис-менеджер 3 день', callback_data='office_manager_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        administration = types.InlineKeyboardButton(text="Назад", callback_data="administration")
        office_manager.add(office_manager_one)
        office_manager.add(office_manager_two)
        office_manager.add(office_manager_three)
        office_manager.add(back, administration)
        bot.edit_message_text('Обучение для Офис-менеджера', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_manager)
    if call.data == "office_manager_one":
        office_manager_one = types.InlineKeyboardMarkup()
        office_manager_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день', callback_data='office_manager_one_material')
        office_manager_one_testing = types.InlineKeyboardButton(text='Тесты Офис-менеджера 1 день', callback_data='office_manager_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_manager = types.InlineKeyboardButton(text="Назад", callback_data="office_manager")
        office_manager_one.add(office_manager_one_material)
        office_manager_one.add(office_manager_one_testing)
        office_manager_one.add(back, office_manager)
        bot.edit_message_text('Обучение для Офис-менеджера день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_manager_one)
    if call.data == "office_manager_two":
        office_manager_two = types.InlineKeyboardMarkup()
        office_manager_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', callback_data='office_manager_two_material')
        office_manager_two_testing = types.InlineKeyboardButton(text='Тесты Офис-менеджера 2 день', callback_data='office_manager_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_manager = types.InlineKeyboardButton(text="Назад", callback_data="office_manager")
        office_manager_two.add(office_manager_two_material)
        office_manager_two.add(office_manager_two_testing)
        office_manager_two.add(back, office_manager)
        bot.edit_message_text('Обучение для Офис-менеджера день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_manager_two)
    if call.data == "office_manager_three":
        office_manager_three = types.InlineKeyboardMarkup()
        office_manager_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день', callback_data='office_manager_three_material')
        office_manager_three_testing = types.InlineKeyboardButton(text='Тесты Офис-менеджера 3 день', callback_data='office_manager_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_manager = types.InlineKeyboardButton(text="Назад", callback_data="office_manager")
        office_manager_three.add(office_manager_three_material)
        office_manager_three.add(office_manager_three_testing)
        office_manager_three.add(back, office_manager)
        bot.edit_message_text('Обучение для Офис-менеджера день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_manager_three)
    elif call.data == "director_assistant":
        director_assistant = types.InlineKeyboardMarkup()
        director_assistant_one = types.InlineKeyboardButton(text='Ассистент руководителя 1 день', callback_data='director_assistant_one')
        director_assistant_two = types.InlineKeyboardButton(text='Ассистент руководителя 2 день', callback_data='director_assistant_two')
        director_assistant_three = types.InlineKeyboardButton(text='Ассистент руководителя 3 день', callback_data='director_assistant_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        administration = types.InlineKeyboardButton(text="Назад", callback_data="administration")
        director_assistant.add(director_assistant_one)
        director_assistant.add(director_assistant_two)
        director_assistant.add(director_assistant_three)
        director_assistant.add(back, administration)
        bot.edit_message_text('Обучение для Ассистента руководителя', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_assistant)
    if call.data == "director_assistant_one":
        director_assistant_one = types.InlineKeyboardMarkup()
        director_assistant_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день', callback_data='director_assistant_one_material')
        director_assistant_one_testing = types.InlineKeyboardButton(text='Тесты Ассистент Руководителя 1 день', callback_data='director_assistant_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_assistant = types.InlineKeyboardButton(text="Назад", callback_data="director_assistant")
        director_assistant_one.add(director_assistant_one_material)
        director_assistant_one.add(director_assistant_one_testing)
        director_assistant_one.add(back, director_assistant)
        bot.edit_message_text('Обучение для Ассистента Руководителя день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_assistant_one)
    if call.data == "director_assistant_two":
        director_assistant_two = types.InlineKeyboardMarkup()
        director_assistant_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день', callback_data='director_assistant_two_material')
        director_assistant_two_testing = types.InlineKeyboardButton(text='Тесты Ассистент Руководителя 2 день', callback_data='director_assistant_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_assistant = types.InlineKeyboardButton(text="Назад", callback_data="director_assistant")
        director_assistant_two.add(director_assistant_two_material)
        director_assistant_two.add(director_assistant_two_testing)
        director_assistant_two.add(back, director_assistant)
        bot.edit_message_text('Обучение для Ассистента Руководителя день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_assistant_two)
    if call.data == "director_assistant_three":
        director_assistant_three = types.InlineKeyboardMarkup()
        director_assistant_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день',
                                                                       callback_data='director_assistant_three_material')
        director_assistant_three_testing = types.InlineKeyboardButton(text='Тесты Ассистент Руководителя 3 день',
                                                                      callback_data='director_assistant_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        director_assistant = types.InlineKeyboardButton(text="Назад", callback_data="director_assistant")
        director_assistant_three.add(director_assistant_three_material)
        director_assistant_three.add(director_assistant_three_testing)
        director_assistant_three.add(back, director_assistant)
        bot.edit_message_text('Обучение для Ассистента Руководителя день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=director_assistant_three)
    elif call.data == "office_director":
        office_director = types.InlineKeyboardMarkup()
        office_director_one = types.InlineKeyboardButton(text='Директор офиса 1 день', callback_data='office_director_one')
        office_director_two = types.InlineKeyboardButton(text='Директор офиса 2 день', callback_data='office_director_two')
        office_director_three = types.InlineKeyboardButton(text='Директор офиса 3 день', callback_data='office_director_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        administration = types.InlineKeyboardButton(text="Назад", callback_data="administration")
        office_director.add(office_director_one)
        office_director.add(office_director_two)
        office_director.add(office_director_three)
        office_director.add(back, administration)
        bot.edit_message_text('Обучение для Директора офиса', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_director)
    if call.data == "office_director_one":
        office_director_one = types.InlineKeyboardMarkup()
        office_director_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день',
                                                                       callback_data='office_director_one_material')
        office_director_one_testing = types.InlineKeyboardButton(text='Тесты Директора Офиса 1 день',
                                                                      callback_data='office_director_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_director = types.InlineKeyboardButton(text="Назад", callback_data="office_director")
        office_director_one.add(office_director_one_material)
        office_director_one.add(office_director_one_testing)
        office_director_one.add(back, office_director)
        bot.edit_message_text('Обучение для Директора Офиса день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_director_one)
    if call.data == "office_director_two":
        office_director_two = types.InlineKeyboardMarkup()
        office_director_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день',
                                                                       callback_data='office_director_two_material')
        office_director_two_testing = types.InlineKeyboardButton(text='Тесты Директора Офиса 2 день',
                                                                      callback_data='office_director_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_director = types.InlineKeyboardButton(text="Назад", callback_data="office_director")
        office_director_two.add(office_director_two_material)
        office_director_two.add(office_director_two_testing)
        office_director_two.add(back, office_director)
        bot.edit_message_text('Обучение для Директора Офиса день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_director_two)
    if call.data == "office_director_three":
        office_director_three = types.InlineKeyboardMarkup()
        office_director_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день',
                                                                       callback_data='office_director_three_material')
        office_director_three_testing = types.InlineKeyboardButton(text='Тесты Директора Офиса 3 день',
                                                                      callback_data='office_director_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        office_director = types.InlineKeyboardButton(text="Назад", callback_data="office_director")
        office_director_three.add(office_director_three_material)
        office_director_three.add(office_director_three_testing)
        office_director_three.add(back, office_director)
        bot.edit_message_text('Обучение для Директора Офиса день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=office_director_three)
    if call.data == "lawyer":
        lawyer = types.InlineKeyboardMarkup()
        jurist = types.InlineKeyboardButton(text="Юрист", callback_data="jurist")
        jurist_director = types.InlineKeyboardButton(text="Руководитель Юр.отдела", callback_data="jurist_director")
        jurist_assistant = types.InlineKeyboardButton(text="Менеджер по сопровождению", callback_data="jurist_assistant")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        back1 = types.InlineKeyboardButton(text="Назад", callback_data="key1")
        lawyer.add(jurist_director)
        lawyer.add(jurist)
        lawyer.add(jurist_assistant)
        lawyer.add(back, back1)
        bot.edit_message_text('Обучение для Юр.Отдела', call.message.chat.id, call.message.message_id,
                                  reply_markup=lawyer)
    elif call.data == "jurist":
        jurist = types.InlineKeyboardMarkup()
        jurist_one = types.InlineKeyboardButton(text='Юрист 1 день', callback_data='jurist_one')
        jurist_two = types.InlineKeyboardButton(text='Юрист 2 день', callback_data='jurist_two')
        jurist_three = types.InlineKeyboardButton(text='Юрист 3 день', callback_data='jurist_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        lawyer = types.InlineKeyboardButton(text="Назад", callback_data="lawyer")
        jurist.add(jurist_one)
        jurist.add(jurist_two)
        jurist.add(jurist_three)
        jurist.add(back, lawyer)
        bot.edit_message_text('Обучение для Юриста', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist)
    if call.data == "jurist_one":
        jurist_one = types.InlineKeyboardMarkup()
        jurist_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день',
                                                                       callback_data='jurist_one_material')
        jurist_one_testing = types.InlineKeyboardButton(text='Тесты Юриста 1 день',
                                                                      callback_data='jurist_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist = types.InlineKeyboardButton(text="Назад", callback_data="jurist")
        jurist_one.add(jurist_one_material)
        jurist_one.add(jurist_one_testing)
        jurist_one.add(back, jurist)
        bot.edit_message_text('Обучение для Юриста день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_one)
    if call.data == "jurist_two":
        jurist_two = types.InlineKeyboardMarkup()
        jurist_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день',
                                                                       callback_data='jurist_two_material')
        jurist_two_testing = types.InlineKeyboardButton(text='Тесты Юриста 2 день',
                                                                      callback_data='jurist_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist = types.InlineKeyboardButton(text="Назад", callback_data="jurist")
        jurist_two.add(jurist_two_material)
        jurist_two.add(jurist_two_testing)
        jurist_two.add(back, jurist)
        bot.edit_message_text('Обучение для Юриста день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_two)
    if call.data == "jurist_three":
        jurist_three = types.InlineKeyboardMarkup()
        jurist_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день',
                                                                       callback_data='jurist_three_material')
        jurist_three_testing = types.InlineKeyboardButton(text='Тесты Юриста 3 день',
                                                                      callback_data='jurist_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist = types.InlineKeyboardButton(text="Назад", callback_data="jurist")
        jurist_three.add(jurist_three_material)
        jurist_three.add(jurist_three_testing)
        jurist_three.add(back, jurist)
        bot.edit_message_text('Обучение для Юриста день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_three)
    elif call.data == "jurist_director":
        jurist_director = types.InlineKeyboardMarkup()
        jurist_director_one = types.InlineKeyboardButton(text='Руководитель Юр.отдела 1 день', callback_data='jurist_director_one')
        jurist_director_two = types.InlineKeyboardButton(text='Руководитель Юр.отдела 2 день', callback_data='jurist_director_two')
        jurist_director_three = types.InlineKeyboardButton(text='Руководитель Юр.отдела 3 день', callback_data='jurist_director_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        lawyer = types.InlineKeyboardButton(text="Назад", callback_data="lawyer")
        jurist_director.add(jurist_director_one)
        jurist_director.add(jurist_director_two)
        jurist_director.add(jurist_director_three)
        jurist_director.add(back, lawyer)
        bot.edit_message_text('Обучение для Руководителя Юр.отдела', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_director)
    if call.data == "jurist_director_one":
        jurist_director_one = types.InlineKeyboardMarkup()
        jurist_director_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день',
                                                                       callback_data='jurist_director_one_material')
        jurist_director_one_testing = types.InlineKeyboardButton(text='Тесты Руководителя Юр.отдела 1 день',
                                                                      callback_data='jurist_director_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_director = types.InlineKeyboardButton(text="Назад", callback_data="jurist_director")
        jurist_director_one.add(jurist_director_one_material)
        jurist_director_one.add(jurist_director_one_testing)
        jurist_director_one.add(back, jurist_director)
        bot.edit_message_text('Обучение для Руководителя Юр.отдела день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_director_one)
    if call.data == "jurist_director_two":
        jurist_director_two = types.InlineKeyboardMarkup()
        jurist_director_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день',
                                                                       callback_data='jurist_director_two_material')
        jurist_director_two_testing = types.InlineKeyboardButton(text='Тесты Руководителя Юр.отдела 2 день',
                                                                      callback_data='jurist_director_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_director = types.InlineKeyboardButton(text="Назад", callback_data="jurist_director")
        jurist_director_two.add(jurist_director_two_material)
        jurist_director_two.add(jurist_director_two_testing)
        jurist_director_two.add(back, jurist_director)
        bot.edit_message_text('Обучение для Руководителя Юр.отдела день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_director_two)
    if call.data == "jurist_director_three":
        jurist_director_three = types.InlineKeyboardMarkup()
        jurist_director_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день',
                                                                       callback_data='jurist_director_three_material')
        jurist_director_three_testing = types.InlineKeyboardButton(text='Тесты Руководителя Юр.отдела 3 день',
                                                                      callback_data='jurist_director_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_director = types.InlineKeyboardButton(text="Назад", callback_data="jurist_director")
        jurist_director_three.add(jurist_director_three_material)
        jurist_director_three.add(jurist_director_three_testing)
        jurist_director_three.add(back, jurist_director)
        bot.edit_message_text('Обучение для Руководителя Юр.отдела день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_director_three)
    elif call.data == "jurist_assistant":
        jurist_assistant = types.InlineKeyboardMarkup()
        jurist_assistant_one = types.InlineKeyboardButton(text='Менеджер по сопровождению 1 день', callback_data='jurist_assistant_one')
        jurist_assistant_two = types.InlineKeyboardButton(text='Менеджер по сопровождению 2 день', callback_data='jurist_assistant_two')
        jurist_assistant_three = types.InlineKeyboardButton(text='Менеджер по сопровождению 3 день', callback_data='jurist_assistant_three')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        lawyer = types.InlineKeyboardButton(text="Назад", callback_data="lawyer")
        jurist_assistant.add(jurist_assistant_one)
        jurist_assistant.add(jurist_assistant_two)
        jurist_assistant.add(jurist_assistant_three)
        jurist_assistant.add(back, lawyer)
        bot.edit_message_text('Обучение для Менеджера по сопровождению', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_assistant)
    if call.data == "jurist_assistant_one":
        jurist_assistant_one = types.InlineKeyboardMarkup()
        jurist_assistant_one_material = types.InlineKeyboardButton(text='Материал для изучения 1 день',
                                                                       callback_data='jurist_assistant_one_material')
        jurist_assistant_one_testing = types.InlineKeyboardButton(text='Тесты Менеджера по сопровождению 1 день',
                                                                      callback_data='jurist_assistant_one_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_assistant = types.InlineKeyboardButton(text="Назад", callback_data="jurist_assistant")
        jurist_assistant_one.add(jurist_assistant_one_material)
        jurist_assistant_one.add(jurist_assistant_one_testing)
        jurist_assistant_one.add(back, jurist_assistant)
        bot.edit_message_text('Обучение для Менеджера по сопровождению  день 1', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_assistant_one)
    if call.data == "jurist_assistant_two":
        jurist_assistant_two = types.InlineKeyboardMarkup()
        jurist_assistant_two_material = types.InlineKeyboardButton(text='Материал для изучения 2 день',
                                                                       callback_data='jurist_assistant_two_material')
        jurist_assistant_two_testing = types.InlineKeyboardButton(text='Тесты Менеджера по сопровождению 2 день',
                                                                      callback_data='jurist_assistant_two_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_assistant = types.InlineKeyboardButton(text="Назад", callback_data="jurist_assistant")
        jurist_assistant_two.add(jurist_assistant_two_material)
        jurist_assistant_two.add(jurist_assistant_two_testing)
        jurist_assistant_two.add(back, jurist_assistant)
        bot.edit_message_text('Обучение для Менеджера по сопровождению  день 2', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_assistant_two)
    if call.data == "jurist_assistant_three":
        jurist_assistant_three = types.InlineKeyboardMarkup()
        jurist_assistant_three_material = types.InlineKeyboardButton(text='Материал для изучения 3 день',
                                                                       callback_data='jurist_assistant_three_material')
        jurist_assistant_three_testing = types.InlineKeyboardButton(text='Тесты Менеджера по сопровождению 3 день',
                                                                      callback_data='jurist_assistant_three_testing')
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        jurist_assistant = types.InlineKeyboardButton(text="Назад", callback_data="jurist_assistant")
        jurist_assistant_three.add(jurist_assistant_three_material)
        jurist_assistant_three.add(jurist_assistant_three_testing)
        jurist_assistant_three.add(back, jurist_assistant)
        bot.edit_message_text('Обучение для Менеджера по сопровождению  день 3', call.message.chat.id, call.message.message_id,
                                  reply_markup=jurist_assistant_three)

    if call.data == "standards":
        standards = types.InlineKeyboardMarkup()
        standards_office = types.InlineKeyboardButton(text="Регламенты Офиса", callback_data="standards_office")
        standards_general = types.InlineKeyboardButton(text="Регламенты Общие", callback_data="standards_general")
        back = types.InlineKeyboardButton(text="Основное меню", callback_data="keyboard")
        keyboard = types.InlineKeyboardButton(text="Назад", callback_data="keyboard")
        testing_standards = types.InlineKeyboardButton(text="Тесты по регламентам", callback_data="testing_standards")
        standards.add(standards_office)
        standards.add(standards_general)
        standards.add(testing_standards)
        standards.add(back, keyboard)
        bot.edit_message_text('Стандарты компании', call.message.chat.id, call.message.message_id,
                                  reply_markup=standards)


bot.polling(none_stop=True)